// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Presentation\Controllers\SkinsController.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using Application.DTOs;
using Application.Services;
using Application.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Presentation.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class SkinsController : ControllerBase
    {
        private readonly ISkinService _skinService;

        public SkinsController(ISkinService skinService)
        {
            _skinService = skinService;
        }

        // GET: api/skins
        [HttpGet]
        public async Task<ActionResult<IEnumerable<SkinResponse>>> GetSkins(CancellationToken ct)
        {
            // TODO: В будущем сюда стоит добавить пагинацию (page, pageSize)
            var skins = await _skinService.GetAllSkinsAsync(ct);
            return Ok(skins);
        }

        // GET: api/skins/5
        [HttpGet("{id:int}")]
        public async Task<ActionResult<SkinResponse>> GetSkin(int id, CancellationToken ct)
        {
            var skin = await _skinService.GetSkinByIdAsync(id, ct);

            if (skin == null)
                return NotFound($"Skin with ID {id} not found");

            return Ok(skin);
        }
    }
}
