// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:02
// File: MinecraftSkinsWebApi\Application\DTOs\BuySkinRequest.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
// Application DTO: BuySkinRequest
// Purpose: Request body for buying a skin. Contains only the SkinId because
// the authenticated user is inferred from the request context (token/claims).

namespace Application.DTOs
{
    // UserId removed from request; user comes from token/context
    public record BuySkinRequest(int SkinId);
}

