// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Application\Services\SkinService.cs
// Purpose: Implements business logic for retrieving skin data and calculating final prices
// ---------------------------------------------------------------------
// Application service: SkinService
// Responsibility:
// - Provide methods to list skins and get single skin details
// - Use IPriceCalculator to compute final prices for presentation
// - Map domain Skin to SkinResponse DTO

using Application.DTOs;
using Application.Services.Interfaces;
using AutoMapper;
using Domain.Repositories;

namespace Application.Services
{


    public class SkinService : ISkinService
    {
        private readonly IMapper _mapper;
        private readonly ISkinRepository _skinRepository;
        private readonly IPriceCalculator _priceCalculator;

        public SkinService(ISkinRepository skinRepository, IPriceCalculator priceCalculator, IMapper mapper)
        {
            _mapper = mapper;
            _skinRepository = skinRepository;
            _priceCalculator = priceCalculator;
        }

        public async Task<IEnumerable<SkinResponse>> GetAllSkinsAsync(CancellationToken cancellationToken)
        {
            var skins = await _skinRepository.GetAllSkinsAsync(cancellationToken);
            var responses = new List<SkinResponse>();

            foreach (var skin in skins)
            {
                if (skin.IsAvailable)
                {
                    var dto = _mapper.Map<SkinResponse>(skin);

                    // Calculate price
                    var finalPrice = await _priceCalculator.CalculateFinalPriceAsync(skin.BasePriceUsd, cancellationToken);

                    // Update DTO with calculated price
                    var withPrice = dto with { FinalPriceUsd = finalPrice };
                    responses.Add(withPrice);
                }
            }

            return responses;
        }

        public async Task<SkinResponse?> GetSkinByIdAsync(int id, CancellationToken cancellationToken)
        {
            var skin = await _skinRepository.GetSkinByIdAsync(id, cancellationToken);
            if (skin == null) return null;

            // Refactored to use Mapper for consistency
            var dto = _mapper.Map<SkinResponse>(skin);

            var finalPrice = await _priceCalculator.CalculateFinalPriceAsync(skin.BasePriceUsd, cancellationToken);

            return dto with { FinalPriceUsd = finalPrice };
        }
    }
}