// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Presentation\Program.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using Application.Services.Interfaces;
using Infrastructure.BTCConnection;
using Application.Services;
using Microsoft.Extensions.Caching.Memory;
using Infrastructure.Repositories;
using Domain.Repositories;
using Infrastructure.Persistence;
using Infrastructure.SeedData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.InMemory;
using SQLitePCL;
using System.Security.Authentication;
using Infrastructure.Handlers;
using Presentation.Extensions;
using Microsoft.AspNetCore.Authentication;
using MinecraftSkins.Application.Mappings;
using Microsoft.Extensions.DependencyInjection;
using AutoMapper;

var builder = WebApplication.CreateBuilder(args);

// Initialize SQLite native provider (safe to call even if not using SQLite)
Batteries.Init();

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddMemoryCache();
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin() // В проде лучше указать конкретный домен
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});
// HttpClient для BTCConnection. api url храните в конфиге (appsettings.json)
// HttpClient for BTCConnection: API URL and key must come from configuration or environment variables.
// Do NOT hardcode API keys in source. Set `BtcApi:Url` and `BtcApi:Key` in secrets or environment.
var btcApiUrl = builder.Configuration.GetValue<string>("BtcApi:Url");
builder.Services.AddAuthentication("MockShceme").
    AddScheme<AuthenticationSchemeOptions, MockAuthoriseHandler>("MockShceme", null);
builder.Services.AddAuthorization();
// Register typed HttpClient and map to IGetRateService so DI provides configured client to BTCConnection
builder.Services.AddHttpClient<IGetRateService, BTCConnection>(client =>
{
    // If the provided URL is absolute, set as BaseAddress; otherwise leave it and BTCConnection will use fallback
    if (Uri.TryCreate(btcApiUrl, UriKind.Absolute, out var uri))
    {
        client.BaseAddress = uri;
    }
});



builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

// Configure EF Core with PostgreSQL if connection string provided
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
var useNpgsql = !string.IsNullOrEmpty(connectionString) && connectionString.Contains("Host=", StringComparison.OrdinalIgnoreCase);

if (useNpgsql)
{
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseNpgsql(connectionString, b => b.MigrationsAssembly("Presentation")));
}
else if (!string.IsNullOrEmpty(connectionString))
{
    // If a connection string exists but not Postgres, assume SQLite
    builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseSqlite(connectionString, b => b.MigrationsAssembly("Presentation")));
}
else
{
    builder.Services.AddDbContext<AppDbContext>(options => options.UseInMemoryDatabase("SkinsDb"));
}

// Repositories: use EF implementations that work with AppDbContext
builder.Services.AddScoped<ISkinRepository, EfSkinRepository>();
builder.Services.AddScoped<IPurchaseRepository, EfPurchaseRepository>();

// Application services
builder.Services.AddScoped<ISkinService, SkinService>();
builder.Services.AddScoped<IPurchaseService, PurchaseService>();

// Price calculator
builder.Services.AddScoped<IPriceCalculator, PriceCalculator>();




// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Apply migrations and seed data only if using Npgsql
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<AppDbContext>();
        if (useNpgsql)
        {
            context.Database.Migrate();
        }
        SeedData.Initialize(services);
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Error migrating or seeding the database");
    }
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

// Centralized exception handler: returns consistent JSON errors and logs exceptions.
app.UseCustomExceptionHandler();

app.UseAuthentication();
app.UseAuthorization();

app.UseCors("AllowAll");
app.MapControllers();

app.Run();

