// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:02
// File: frontend\src\api.js
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
import axios from 'axios';


const api = axios.create({
    baseURL: 'http://localhost:5042/api', 
    headers: {
        'Content-Type': 'application/json'
    }
});

// РРќРўР•Р Р¦Р•РџРўРћР  (РџР•Р Р•РҐР’РђРўР§РРљ)
// РџРµСЂРµРґ РєР°Р¶РґС‹Рј Р·Р°РїСЂРѕСЃРѕРј СЌС‚РѕС‚ РєРѕРґ РІС‹РїРѕР»РЅСЏРµС‚СЃСЏ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё
api.interceptors.request.use((config) => {
    // 1. РџС‹С‚Р°РµРјСЃСЏ РЅР°Р№С‚Рё ID РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ РІ С…СЂР°РЅРёР»РёС‰Рµ Р±СЂР°СѓР·РµСЂР°
    let currentUserId = localStorage.getItem('mockUserId');

    // 2. Р•СЃР»Рё ID РЅРµС‚ (РїРµСЂРІС‹Р№ Р·Р°РїСѓСЃРє), СЃС‚Р°РІРёРј "1" РїРѕ СѓРјРѕР»С‡Р°РЅРёСЋ, С‡С‚РѕР±С‹ РІСЃС‘ СЂР°Р±РѕС‚Р°Р»Рѕ СЃСЂР°Р·Сѓ
    if (!currentUserId) {
        currentUserId = "1";
        localStorage.setItem('mockUserId', "1");
    }

    // 3. Р”РѕР±Р°РІР»СЏРµРј Р·Р°РіРѕР»РѕРІРѕРє, РєРѕС‚РѕСЂС‹Р№ Р¶РґРµС‚ РІР°С€ MockAuthoriseHandler
    // Р¤РѕСЂРјР°С‚: "Bearer {int}"
    config.headers.Authorization = `Bearer ${currentUserId}`;

    console.log(`[API Request] Sending as User ID: ${currentUserId}`);
    
    return config;
});

export default api;
