// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:02
// File: frontend\src\App.jsx
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
import { useState, useEffect } from 'react';
import api from './api';
import './App.css';

function App() {
  const [skins, setSkins] = useState([]);
  const [myPurchases, setMyPurchases] = useState([]);
  const [statusMsg, setStatusMsg] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('shop');

  const loadSkins = async () => {
    try {
      setLoading(true);
      const res = await api.get('/skins');
      setSkins(res.data);
      setStatusMsg('вњ… РЎРїРёСЃРѕРє СЃРєРёРЅРѕРІ РѕР±РЅРѕРІР»РµРЅ');
    } catch (err) {
      console.error(err);
      setStatusMsg('вќЊ РћС€РёР±РєР° Р·Р°РіСЂСѓР·РєРё СЃРєРёРЅРѕРІ');
    } finally {
      setLoading(false);
    }
  };

  const loadHistory = async () => {
    try {
      setLoading(true);
      const res = await api.get('/purchases/history');
      setMyPurchases(res.data);
      setStatusMsg('рџ“Љ РСЃС‚РѕСЂРёСЏ РїРѕРєСѓРїРѕРє Р·Р°РіСЂСѓР¶РµРЅР°');
    } catch (err) {
      console.error(err);
      setStatusMsg('вќЊ РћС€РёР±РєР° Р·Р°РіСЂСѓР·РєРё РёСЃС‚РѕСЂРёРё');
    } finally {
      setLoading(false);
    }
  };

  const buySkin = async (skinId) => {
    try {
      setLoading(true);
      await api.post('/purchases', { skinId });
      setStatusMsg(`рџЋ‰ РЎРєРёРЅ #${skinId} СѓСЃРїРµС€РЅРѕ РєСѓРїР»РµРЅ!`);
      loadHistory();
    } catch (err) {
      console.error(err);
      setStatusMsg('вќЊ РћС€РёР±РєР° РїСЂРё РїРѕРєСѓРїРєРµ');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSkins();
    loadHistory();
  }, []);

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleString('ru-RU', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div className="app">
      {/* РЁР°РїРєР° */}
      <header className="header">
        <div className="header-content">
          <h1 className="logo">рџЋ® SkinShop</h1>
        </div>
      </header>

      {/* РЎС‚Р°С‚СѓСЃ СЃРѕРѕР±С‰РµРЅРёРµ */}
      {statusMsg && (
        <div className={`status-message ${statusMsg.includes('вќЊ') ? 'error' : 'success'}`}>
          {statusMsg}
        </div>
      )}

      {/* РўР°Р±С‹ */}
      <div className="tabs">
        <button 
          className={`tab ${activeTab === 'shop' ? 'active' : ''}`}
          onClick={() => setActiveTab('shop')}
        >
          рџ›’ РњР°РіР°Р·РёРЅ
        </button>
        <button 
          className={`tab ${activeTab === 'history' ? 'active' : ''}`}
          onClick={() => setActiveTab('history')}
        >
          рџ“њ РСЃС‚РѕСЂРёСЏ РїРѕРєСѓРїРѕРє
        </button>
      </div>

      {/* РљРѕРЅС‚РµРЅС‚ */}
      <main className="main-content">
        {/* РњР°РіР°Р·РёРЅ */}
        {activeTab === 'shop' && (
          <div className="shop">
            <div className="shop-header">
              <h2>Р”РѕСЃС‚СѓРїРЅС‹Рµ СЃРєРёРЅС‹</h2>
              <button onClick={loadSkins} className="refresh-btn" disabled={loading}>
                {loading ? 'вЏі Р—Р°РіСЂСѓР·РєР°...' : 'рџ”„ РћР±РЅРѕРІРёС‚СЊ'}
              </button>
            </div>

            <div className="skins-grid">
              {skins.map(skin => (
                <div key={skin.id} className="skin-card">
                  <div className="skin-info">
                    <h3>{skin.name}</h3>
                    <div className="skin-price">
                      <span className="price-label">Р¦РµРЅР°:</span>
                      <span className="price-value">${skin.finalPriceUsd}</span>
                    </div>
                  </div>
                  <button 
                    onClick={() => buySkin(skin.id)}
                    className="buy-btn"
                    disabled={loading}
                  >
                    {loading ? '...' : 'РљСѓРїРёС‚СЊ'}
                  </button>
                </div>
              ))}
              {skins.length === 0 && !loading && (
                <div className="empty-state">
                  <p>рџ›ЌпёЏ РЎРєРёРЅС‹ РІСЂРµРјРµРЅРЅРѕ РѕС‚СЃСѓС‚СЃС‚РІСѓСЋС‚</p>
                </div>
              )}
            </div>
          </div>
        )}

        {/* РСЃС‚РѕСЂРёСЏ РїРѕРєСѓРїРѕРє */}
        {activeTab === 'history' && (
          <div className="history">
            <div className="history-header">
              <h2>РњРѕРё РїРѕРєСѓРїРєРё</h2>
              <button onClick={loadHistory} className="refresh-btn" disabled={loading}>
                {loading ? 'вЏі Р—Р°РіСЂСѓР·РєР°...' : 'рџ”„ РћР±РЅРѕРІРёС‚СЊ'}
              </button>
            </div>

            <div className="purchases-list">
              {myPurchases.map((purchase, index) => (
                <div key={purchase.id || index} className="purchase-item">
                  <div className="purchase-icon">рџЋЃ</div>
                  <div className="purchase-details">
                    <div className="purchase-title">
                      РџРѕРєСѓРїРєР° #{purchase.id}
                      <span className="purchase-badge">РЎРєРёРЅ #{purchase.skinId}</span>
                    </div>
                    <div className="purchase-meta">
                      <span className="purchase-date">{formatDate(purchase.purchaseAt)}</span>
                      <span className="purchase-amount">${purchase.paidAmountUsd}</span>
                      <span className="purchase-btc">{purchase.btcPriceAtMoment} BTC</span>
                    </div>
                  </div>
                </div>
              ))}
              {myPurchases.length === 0 && !loading && (
                <div className="empty-state">
                  <p>рџ“­ РЈ РІР°СЃ РїРѕРєР° РЅРµС‚ РїРѕРєСѓРїРѕРє</p>
                  <button onClick={() => setActiveTab('shop')} className="shop-link">
                    РџРµСЂРµР№С‚Рё РІ РјР°РіР°Р·РёРЅ
                  </button>
                </div>
              )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
