param(
    [switch]$Commit
)

$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$repo = Resolve-Path . | Select-Object -ExpandProperty Path
$patterns = @("*.cs","*.js","*.jsx")
$excludeDirs = @('.git','node_modules','bin','obj','.vs','.vscode','packages')

Write-Host "Scanning repository for source files..."
$files = Get-ChildItem -Path $repo -Recurse -File -Include $patterns -ErrorAction SilentlyContinue |
    Where-Object {
        $skip = $false
        foreach ($d in $excludeDirs) { if ($_.FullName -like "*\$d\*") { $skip = $true; break } }
        -not $skip
    }

$modified = @()
foreach ($f in $files) {
    try {
        $content = Get-Content -Path $f.FullName -Raw -ErrorAction Stop
    } catch {
        Write-Warning "Cannot read $($f.FullName): $_"
        continue
    }

    if ($content -match 'AUTOGENERATED HEADER') {
        continue
    }

    $rel = $f.FullName.Substring($repo.Length + 1).Replace('\\','/')

    $headerLines = @()
    $headerLines += "// ---------------------------------------------------------------------"
    $headerLines += "// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at $now"
    $headerLines += "// File: $rel"
    $headerLines += "// Purpose: TODO - fill file description"
    $headerLines += "// ---------------------------------------------------------------------"
    $headerLines += ""

    $newContent = ($headerLines -join "`r`n") + $content

    try {
        Set-Content -Path $f.FullName -Value $newContent -Encoding UTF8 -ErrorAction Stop
        $modified += $rel
        Write-Host "Updated: $rel"
    } catch {
        Write-Warning ("Failed to write {0}: {1}" -f $rel, $_)
    }
}

Write-Host "Files modified: $($modified.Count)"

if ($Commit) {
    if (Get-Command git -ErrorAction SilentlyContinue) {
        try {
            git add -A
            $status = git status --porcelain
            if ($status) {
                git commit -m "chore: add autogenerated file headers ($now)"
                Write-Host "Committed changes."
            } else {
                Write-Host "No changes to commit."
            }
        } catch {
            Write-Warning ("Git commit failed: {0}" -f $_)
        }
    } else {
        Write-Warning "Git is not available in PATH. Skipping commit."
    }
}

Write-Host "Done."
