// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Infrastructure\DbContext\AppDbContext.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Domain.Models;

namespace Infrastructure.Persistence
{
    public class AppDbContext: DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<Skin> Skins { get; set; } = null!;
        public DbSet<Purchase> Purchases { get; set; } = null!;
    }
}

