// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Application\Services\Interfaces\IGetRateService.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
// Application service interface: IGetRateService
// Purpose: Abstraction for obtaining current BTC/USD price. Implementations
// may call external APIs, use caching, and support CancellationToken.

using System.Threading;
using System.Threading.Tasks;

namespace Application.Services.Interfaces
{
    public interface IGetRateService
    {
        Task<decimal> GetRateAsync(CancellationToken cancellationToken = default);
    }
}

