// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Application\Services\Interfaces\IPriceCalculator.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Application.Services.Interfaces
{
    public interface IPriceCalculator
    {
        Task<decimal> CalculateFinalPriceAsync(decimal basePriceUsd, CancellationToken cancellationToken = default);
    }
}

