// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Domain\Repositories\ISkinRepository.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Domain.Models;
namespace Domain.Repositories
{
    public interface ISkinRepository
    {
        Task<IEnumerable<Skin>> GetAllSkinsAsync(CancellationToken _token);

        Task<Skin?> GetSkinByIdAsync(int id, CancellationToken _token);
        
    }
}

