// ---------------------------------------------------------------------
// AUTOGENERATED HEADER: Added by add_file_headers.ps1 at 2026-02-16 09:45:27
// File: MinecraftSkinsWebApi\Presentation\Migrations\20260216_ChangeUserIdToText.cs
// Purpose: TODO - fill file description
// ---------------------------------------------------------------------
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Presentation.Migrations
{
    /// <inheritdoc />
    public partial class ChangeUserIdToText : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Ensure UserId is text for string storage (handles any previous integer attempts)
            migrationBuilder.Sql("ALTER TABLE \"Purchases\" ALTER COLUMN \"UserId\" TYPE text USING (\"UserId\"::text)");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Revert to text (no-op, already text by design)
            migrationBuilder.Sql("ALTER TABLE \"Purchases\" ALTER COLUMN \"UserId\" TYPE text");
        }
    }
}

